# Generated by Django 2.1.7 on 2019-04-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='metadata',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='grade',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
