# Generated by Django 2.1.7 on 2019-04-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_questionoption_sorting_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='about',
            field=models.TextField(default='pressing campus issues'),
        ),
    ]
