# Generated by Django 2.1.7 on 2019-04-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
