# Generated by Django 2.2 on 2019-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_authorizedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('U', 'Unread'), ('R', 'Read & Not Implemented'), ('I', 'Read & Implemented')], default='U', max_length=1),
        ),
    ]
